extends: stylelint-config-standard

reportDescriptionlessDisables: true

reportInvalidScopeDisables: true

reportNeedlessDisables: true

ignoreFiles:
  - dist/**/*.css
  - src/gadgets/prism-core/MediaWiki:Gadget-prism-coy.css
  - src/gadgets/prism-core/MediaWiki:Gadget-prism-line-numbers.css
  - src/gadgets/prism-core/MediaWiki:Gadget-prism-inline-color.css
  - src/gadgets/prism-plugin-match-braces/MediaWiki:Gadget-prism-plugin-match-braces.css
  - src/gadgets/prism-plugin-previewers/MediaWiki:Gadget-prism-plugin-previewers.css

rules:
  selector-id-pattern: null
  selector-class-pattern: null
  no-descending-specificity: null
  number-max-precision: null
  selector-no-vendor-prefix: null
  value-no-vendor-prefix: null
  at-rule-no-vendor-prefix: null
  media-feature-name-no-vendor-prefix: null
  property-no-vendor-prefix: null
  selector-attribute-quotes: null
  function-no-unknown:
    - true
    - ignoreFunctions:
        - alpha
  comment-empty-line-before: null
  selector-type-no-unknown:
    - true
    - ignoreTypes:
        - ogvjs
  no-duplicate-selectors: null
  declaration-property-value-no-unknown: true
