/* eslint-env browser */
"use strict";
/**
 * Generated by scripts/generatePolyfill.js
 * Options:
 *     targetChromiumVersion: "$$$TARGET_CHROMIUM_VERSION$$$"
 *     targetUA: "$$$TARGET_UA$$$"
 *     unrecognizableFeaturesFeatures: "scripts/generatePolyfill/unrecognizableFeatures.json"
 *     flaggableFeatures: "$$$FLAGGABLE_FEATURES$$$"
 */
(() => {
    const script = document.createElement("script");
    script.src = "https://polyfill.io/v3/polyfill.js?ua=$$$UA$$$&features=$$$FEATURES$$$";
    script.async = true;
    const polyfillPromise = new Promise((res) => {
        script.addEventListener("load", () => res(), {
            once: true,
        });
        script.addEventListener("error", () => res(), {
            once: true,
        });
    });
    Object.defineProperty(window, "polyfillPromise", {
        configurable: false,
        enumerable: true,
        writable: false,
        value: polyfillPromise,
    });
})();
