"use strict";
/**
 * Generated by scripts/generatePolyfill/index.js
 * Options:
 *     targetChromiumVersion: "$$$TARGET_CHROMIUM_VERSION$$$"
 *     targetUA: "$$$TARGET_UA$$$"
 *     unrecognizableFeaturesFeatures: "scripts/generatePolyfill/unrecognizableFeatures.json"
 *     flaggableFeatures: $$$FLAGGABLE_FEATURES$$$
 */
(() => {
    const script = document.createElement("script");
    script.src = "https://polyfill.alicdn.com/v3/polyfill.js?features=$$$FEATURES$$$";
    script.async = false;
    const polyfillPromise = new Promise((res) => {
        script.addEventListener("load", () => res(), {
            once: true,
        });
        script.addEventListener("error", () => res(), {
            once: true,
        });
    });
    Reflect.defineProperty(window, "polyfillPromise", {
        configurable: false,
        enumerable: true,
        writable: false,
        value: polyfillPromise,
    });
    document.head.appendChild(script);
})();
