name: auto_fix

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  actions: write

jobs:
  auto_fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        name: Checkout main repo
        with:
          show-progress: false
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Installing the dependencies
        uses: AnnAngela/cached_node-modules@095ea9ae366bc4a18c0f653aed2008d35660317d # v6
        with:
          command: npm run ci
      - name: Git config
        run: node scripts/postCommit/prepareGit.js
      - run: npm run format
      - name: Show git status & push
        run: node scripts/postCommit/push.js
