name: auto_fix

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  auto_fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Checkout main repo
        with:
          fetch-depth: 0
          show-progress: false
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Installing the dependencies
        uses: AnnAngela/cached_node-modules@v3
        with:
          command: npm run ci
      - name: Git config
        run: node scripts/postCommit/prepareGit.js
      - run: npm run format
      - name: Show git status & push
        run: node scripts/postCommit/push.js
