name: auto_fix

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  actions: write

jobs:
  auto_fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        name: Checkout main repo
        with:
          show-progress: false
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Installing the dependencies
        uses: AnnAngela/cached_node-modules@8336d5acec06f1670b1097dc0b424527a8481659 # v6
        with:
          command: npm run ci
      - name: Git config
        run: node scripts/postCommit/prepareGit.js
      - run: npm run format
      - name: Show git status & push
        run: node scripts/postCommit/push.js
