name: Detect hardcoded-outdated NPM packages
permissions:
  contents: read
  issues: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * * # Every 07:00 CST

concurrency: detectHardcodedOutdatedNPMPackages

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generateConfiguration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Installing the dependencies
        uses: AnnAngela/cached_node-modules@095ea9ae366bc4a18c0f653aed2008d35660317d # v6
        with:
          command: npm run ci
      - name: Detect hardcoded-outdated NPM packages
        run: node scripts/detectHardcodedOutdatedNPMPackages/index.js
